### ISSUE TITLE
Can you make the function to ignore specific directories?

### ISSUE THREAD

**Issue by PetersonLian** [xahlee/xah-find#12]
Can you make the function to ignore specific directories?
能否让此函数在使用的时候，略过一些特定文件夹(不搜索这些文件夹)？

**Comment by xahlee** [comment]
M-x customize-group, then xah-find, the change Show Value Xah Find Dir Ignore Regex List.
That should do. Or, directly put this in your init after loading xah-find:

(setq xah-find-dir-ignore-regex-list [ "\\.git/" "etc"])

**Comment by PetersonLian** [comment]
cool
